#This action file is to trigger the playwright api tests from https://github.com/cv-library/rl-php-api/blob/development/.github/workflows/deploy-to-staging-e2e.yml
name: 'Run Playwright API tests'
description: 'Run Playwright API tests on github actions'
inputs:
    tag-name:
        description: 'API tests scenarios tag name'
        required: true
    branch-name:
        description: 'Branch name to run the API tests against'
        required: true
    github-token:
        description: 'Github access token'
        required: true

runs:
    using: 'composite'
    steps:
        - name: Checkout Code
          uses: actions/checkout@v4
          with:
              repository: cv-library/playwright-sample-api
              path: .
              token: ${{ inputs.github-token }}

        - name: Executing the playwright API tests
          shell: bash
          run: |
              npm i
              npm install -D @playwright/test@latest

              TAG_NAME=${{ inputs.tag-name }}
              BRANCH=${{ inputs.branch-name }}
              echo "BRANCH_NAME=$(echo "${BRANCH}")"
              echo "TAG_NAME=$(echo "${TAG_NAME}")"
              BRANCH_NAME=${BRANCH} test_env=staging npx playwright test --grep ${TAG_NAME}
